Repository elementsinteractive/sheriff, pull requests merged in 2024-12, with the labels that each got.

#38 feat(#36): post to multiple slack channels
  internal/patrol/patrol.go
  internal/publish/to_slack.go
  internal/publish/to_slack_test.go
Labels: feature

#40 feat(#31): Mark outdated acknowledged vulnerabilities in the issue report
  internal/patrol/patrol.go
  internal/patrol/patrol_test.go
  internal/publish/to_gitlab.go
  internal/scanner/vulnscanner.go
Labels: feature

#43 ci: fix ci variable indentation
  gitlab/templates/sheriff.gitlab-ci.yml
Labels: CI

#44 fix: project config compatibility
  internal/config/project.go
Labels: fix
