Repository elementsinteractive/sheriff, pull requests merged in 2025-06, with the labels that each got.

#55 feat: ignore project list
  README.md
  internal/cli/patrol.go
  internal/config/patrol.go
  internal/config/patrol_test.go
  internal/config/project.go
  internal/patrol/patrol.go
  internal/patrol/patrol_test.go
Labels: feature

#58 fix: ignore fetched projects with ignore list
  internal/patrol/patrol.go
  internal/patrol/patrol_test.go
Labels: fix

#59 ci: add lgtm code reviewer
  .github/workflows/lgtm.yml
  lgtm.toml
Labels: CI
